[mcp_servers.serena]
type = "stdio"
command = "uvx"
args = [ 
    "--from", "git+https://github.com/oraios/serena", 
    "serena", "start-mcp-server", 
    "--context", "ide-assistant", 
    "--enable-web-dashboard", "false", 
    "--project", "." 
]

[mcp_servers.context7]
type = "stdio"
command = "npx"
args = [ "-y", "@upstash/context7-mcp" ]

[mcp_servers.context7.env]
UPSTASH_REDIS_REST_URL = "https://wise-jaguar-106351.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "gQAAAAAAAZ9vAAIgcDFjNDFmMDJhZTA1ZjA0Yzg0YmYyZmE5YmM2M2U3NzU3Yg"

